name: Test SSH Connection

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  test-ssh:
    runs-on: ubuntu-latest  # Use a Linux runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Debug Environment
        run: |
          echo "Checking home directory..."
          ls -la $HOME
          echo "Checking .ssh directory..."
          mkdir -p ~/.ssh
          ls -la ~/.ssh
          
      - name: Debug SSH Key Setup
        run: |
          echo "Checking if SSH key is loaded..."
          if [[ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]]; then
            echo "ERROR: SSH_PRIVATE_KEY is empty or not accessible!"
            exit 1
          else
            echo "SSH_PRIVATE_KEY is loaded."
          fi

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your-server.com >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -v -o StrictHostKeyChecking=no user@your-server.com "echo 'SSH Connection Successful'"
